title: Thiago Casagrande # your name (or website title) here
logo: "/images/eu.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Oi! Meu nome é Thiago, sou matemático e com experiência em análise de dados e aprendizado de máquina.
  # Hello! I'm Thiago, a mathematician with some experience in data analysis and machine learning.  
  <br><br>
  Aqui você encontra uma coleção dos meus projetos acadêmicos e pessoais. Sinta-se a vontade para entrar em contato comigo, caso tenha alguma dúvida sobre eles.
  # Here, you will find a collection of my projects. Feel free to reach me out if you have any questions on it.
  <br><br>
  <a href="https://www.linkedin.com/in/thiago-peres-casagrande-a3b631186">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
